### ISSUE TITLE
Build Validator Object

### ISSUE THREAD

**Issue by Clivern** [Clivern/Kangaroo#3]

**Comment by Ikhiloya** [comment]
Hi @Clivern, I'll love to take this one. But I'll need to understand what this project is all about. A Readme file would be useful.

**Comment by Clivern** [comment]
Hi @Ikhiloya, the project is about http://json-schema.org/ validator. in general it allows you to validate a payload of data by providing a json file to validate against. it makes building api services handy especially for statically typed language like java. There is already implementation on all programming languages.

I did some stuff on this branch https://github.com/Clivern/Kangaroo/tree/feature/schema. But i can confirm that stuff still a bit vague since i am still building the architecture.

If you need something a bit clear and java for hacktoberfest, please check this https://github.com/Clivern/wit-java/issues
